### ISSUE TITLE
Integration of this library with Apache Cassandra

### ISSUE THREAD

**Issue by smiklosovic** [jpmsilva/jsystemd#11]
Hi @jpmsilva,

I am from Apache Cassandra project and we evaluate the integration of this library with Cassandra. It is great that this library is Apache 2.0 licensed and it is actively developed. I looked around and this is basically the only library which is Apache 2.0 and it is actively developed.

Casandra 5.1 (current trunk) is supporting Java 11 and Java 17. I see you depend on Java 17 for 3.x releases. I looked into 2.0.1 for that reason but JNA is of version 5.7.0. I think we are using 5.9.0 and we want to update to 5.13.0 sooner or later.

Do you think you could patch 2.0.1 for us and release it as 2.0.2 or similar which would still support Java 11 but it would have updated and aligned JNA with our project?

Regards

**Comment by jpmsilva** [comment]
Hi @smiklosovic 

jsystemd depends on JNA 5.7.0 merely as a baseline, because I have to develop and test it against some specific version, but it actually works with newer minor versions of JNA. Reading the [changelog](https://github.com/java-native-access/jna/blob/master/CHANGES.md) from going to 5.7.0 to 5.9.0 (and indeed, 5.14.0) I see no breaking changes that would indicate that you cannot swap one with the other, so I think there is nothing stopping you from swapping one version with the other.

Indeed, if your project uses JNA 5.9.0 and you include jsystemd 2.01 that brings in JNA 5.7.0, your version [should "win"](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#transitive-dependencies) since it's nearest to your project:

> Dependency mediation - this determines what version of an artifact will be chosen when multiple versions are encountered as dependencies. Maven picks the "nearest definition". That is, it uses the version of the closest dependency to your project in the tree of dependencies. You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.

You might also want to explicit manage your dependency versions with a `<dependencyManagement>` block, in which case whatever your transitive dependencies might declare is explicitly overridden by the versions you choose to use in your project.

It might be more explicit jsystemd accepts versions greater than JNA 5.7.0 if we use [version ranges](https://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-project-dependencies.html#pom-relationships-sect-version-ranges), but as of right now, I'm not seeing major benefits of releasing a new version of the 2.x line just to bump the JNA version.

Could you perhaps expand a bit on why this would be beneficial?

Thank you!

**Comment by jpmsilva** [comment]
Do let me know if there is any additional clarification I can provide.
